# Generated by Django 3.2.9 on 2022-02-16 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('contact_date', models.DateField(blank=True, default=datetime.date(2022, 2, 16))),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
