# Generated by Django 3.2.9 on 2022-02-16 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 58, 35, 885303, tzinfo=utc)),
        ),
    ]
