# Generated by Django 3.2.9 on 2021-11-19 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('area', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/{%Y/%m/%d/')),
                ('photo_two', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_three', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_four', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_five', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_six', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
